name: worthless animals of the wild
favicon: null
layout_spectrum: 0.2486
typography_spectrum: 0.4817470065318048
title: 'a story about chickens, poop and envy'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.965998328756541
purpose: []
