name: FernandoAriasvanOordt
favicon: null
layout_spectrum: 0.4277
typography_spectrum: 0.72058
title: how to slaught chickens the proper way
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.08211615891195834
  lightness: 0.0625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
