typography_spectrum: 0.4817470065318048
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.875
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.965998328756541
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2486
analytics:
  google: null
  facebook: null
  twitter: null
name: worthless animals of the wild
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: about the book
    id: 9f1d8543-9af2-4932-a6f4-05a9cb6ae926
    type: content
favicon: null
title: 'a story about chickens, poop and envy'
purpose: []
