name: FernandoAriasvanOordt
favicon: null
layout_spectrum: 0.35406
typography_spectrum: 0.72058
title: how to slaught chickens the proper way
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191411'
    - '#7b5f5c'
    - '#a30000'
    - '#ecc7b6'
    - '#eb7200'
  brandStrength: 0.08211615891195834
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
