name: FernandoAriasvanOordt
favicon: null
layout_spectrum: 0.9445
typography_spectrum: 0.72058
title: 'Chickens, Embezzlement and Bankruptcy '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191411'
    - '#7b5f5c'
    - '#a30000'
    - '#ecc7b6'
    - '#eb7200'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.75
purpose: []
