layout_spectrum: 0.5701287037227303
typography_spectrum: 0.4817470065318048
color:
  brandColors:
    - '#FF6600'
    - '#C13B00'
    - '#5E6D70'
    - '#424E4F'
    - '#1B1D1E'
  brandStrength: 0.6980199594981968
  lightness: 0.3124290050473064
  saturation: 0.19146190397441387
  rhythmicContrast: 0.965998328756541
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: worthless animals of the wild
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'a story about chickens, poop and envy'
purpose: []
