typography_spectrum: 0.72058
color:
  brandColors:
    - '#191411'
    - '#7b5f5c'
    - '#a30000'
    - '#ecc7b6'
    - '#eb7200'
  brandStrength: 0.25
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.27067
analytics:
  google: null
  facebook: null
  twitter: null
name: Fernando Arias van Oordt
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Chickens, Embezzlement and Bankruptcy '
purpose: []
